### PR TITLE
Org card design

### PR DESCRIPTION
**Pull request by bryan-robitaille**
Styled org chart 'Go To Me' button as well org chart cards to include Team name and Title.
Styled mini chart to remove as much white space as possible while leaving room for layout.
 
Before:
Selection_027

After:
Selection_030

### CODE REVIEW

**Comment by bryan-robitaille** [comment]
The 'Go to Me' button is behaving weird now in that it's moving the org chart selection to the 'me' but does not load the profile of the user.  Can be quickly fixed by modifying the onclick of that button but...
Wondering if we even need this button anymore??

**Comment by bryan-robitaille** [comment]
Removed 'Got to Me' button.
What do you think @piet0024 
Selection_031

**Comment by piet0024** [comment]
Looks good 👍 
Things we could look at in the future, is adding some more padding to the placement of the cards and lines so it's a bit clearer of who is connected to who. 

Also I realised (from what I added :S ) that as you're clicking through the org chart cards, going back on the browser does not trigger a re-render on the org chart. Perhaps we can look into that later.

**Comment by piet0024** [comment]
Before this is merged I'm going to check the snapshot tests.

**Pull request merged**
